version: "3.9" # Versão do Docker Compose

services:
  postgres: # Nome do serviço
    image: postgres:latest # Imagem do PostgreSQL
    container_name: finance_postgres # Nome do container
    ports:
      - "5432:5432" # Porta 5432 no host mapeada para 5432 no container
    environment:
      POSTGRES_USER: neondb_owner # Usuário do PostgreSQL
      POSTGRES_PASSWORD: password # Senha do PostgreSQL
      POSTGRES_DB: finance-ai # Nome do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume persistente

volumes:
  postgres_data: # Volume nomeado para persistência dos dados
